### ISSUE TITLE
David is down 🙀

### ISSUE THREAD

**Issue by daviddias** [alanshaw/david-dm#2]
https://david-dm.org/
![image](https://user-images.githubusercontent.com/1211152/99181747-703aaa00-2728-11eb-9fa5-f9102b5fe790.png)

**Comment by Martii** [comment]
``` html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Internal Server Error</pre>
</body>
</html>
```
... here and TLS certificate expired on November 16, 2020 from LetsEncrypt.

**Comment by alanshaw** [comment]
I've deployed david to digitalocean apps using the updated dockerfile.

The Letsencrypt API got turned off so a new SSL cert was not issued. I also had to update david so it works with node 14 (was using node 6 before).

SSL certs, OS updates and configuration are now no longer my problem so hooray for that. It also auto deploys. Lets hope it works 🤞
